name: Test

on:
  - push
  - pull_request

env:
  COMPOSER_FLAGS: --ansi --no-interaction --no-progress --prefer-dist

jobs:
  tests:
    name: Test psalm.phar

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php-version:
          - "8.0"
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: none
          php-version: ${{ matrix.php-version }}

      - name: Get composer cache directory
        id: composercache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Restore cached dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composercache.outputs.dir }}
          key: php-${{ matrix.php-version }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: php-${{ matrix.php-version }}-composer-

      - name: Install latest dependencies
        run: composer update ${{ env.COMPOSER_FLAGS }}

      - name: Run Psalm
        run: vendor/bin/psalm.phar
